### ISSUE TITLE
Playback controls missing after recent update

### ISSUE THREAD

**Issue by Macca-MK** [radiant-player/radiant-player-mac#523] opened 2016-03-24 10:51 UTC
Hi

Not sure if anyone else has had the problem, but since updating to 1.7.3 today, the playback controls are missing in the window. Not sure what happened, and I can still control playback via the media keys on my MacBook, but I can't see the UI buttons for any of the playback controls, including the queue button. The whole toolbar is empty except for the track info and progress bar (on hover)

Any ideas how to rectify?

Thanks
Andrew 

<img width="841" alt="screen shot 2016-03-24 at 10 49 37" src="https://cloud.githubusercontent.com/assets/18049278/14015047/36aa5dc6-f1ae-11e5-97e3-57b326650e86.png">

**Comment by redbullcat** [comment] 2016-03-24 11:18
Same issue, except the entire UI is kinda messed up for me. 
![screen shot 2016-03-24 at 11 16 59](Screenshot)

**Comment by Macca-MK** [comment] 2016-03-24 12:50
I've just noticed some other UI quirks since your post as well - seems to be a slightly bigger problem than I first thought.

**Comment by chrismou** [comment] 2016-03-24 13:43
I'm not seeing this at all, so if you've only just upgraded I wonder if this could be a cache issue. 

That said, @redbullcat custom theme enabled, so there shouldn't be any CSS overrides applied to the play bar.

Any info you can provide would be helpful. Also, try opening Google Music in Safari and see if you're seeing the same issue there, try clearing the Safari cache, restart your Mac, etc.  If this was affecting everyone I'd expect to have seen more reports, as 1.7.3 has been out for over a week now (and the changes were minor and only applied to the dark themes).

**Comment by louisroy** [comment] 2016-03-24 14:19
Having the same problem over here.

Google Play Music is also broken on Safari/Yosemite. Clearing the cache and restarting do not solve the problem.

![Screenshot](http://i.imgur.com/BBwlg3Q.png)

Looks like the problem is related to Safari 8.*. I'm guessing Google Play Music has removed all of its -webkit-* vendor prefixes which causes issues with flex boxes everywhere and ultimately breaks the layout.

The only way to fix this is to upgrade to Safari 9 and/or El Capitan.

**Comment by chrismou** [comment] 2016-03-24 14:21
@Macca-MK @redbullcat Are you guys also on Yosemite?

**Comment by Macca-MK** [comment] 2016-03-24 15:24
Hi

I'm on Yosemite (on this work MacBook) and el Capitan at home. I can see later today if it's working at home differently to here, so will get back to you on that.

I tried clearing caches in Safari but no joy in Radiant - still same UI bugs. However, in Safari (I'm using Safari 9.1) Play Music is working fine, exactly as you would expect it to and not like @louisroy's screenshot above. (see my screenshot)
<img width="1550" alt="screen shot 2016-03-24 at 15 22 52" src="https://cloud.githubusercontent.com/assets/18049278/14021645/4ddca636-f1d4-11e5-91c7-d7c017028b40.png">

Will let you know about El Capitan and appreciate your help! I Love Radiant, it's been my go to player for ages as it's such a superior experience to Play Music in the browser, so anythign I can do to help resolve I will. 

Cheers
Andrew

**Comment by jlp78** [comment] 2016-03-24 21:47
On Yosemite.  Just updated because all of a sudden my music stopped playing (but it continued to think it was playing... just flipping through songs in the play list).  Figured I would restart Radiant Player and did so... it prompted me to update, so I thought that was maybe the problem and did so.  Results were that I could play music again, but the play/pause buttons were missing, as well as the controls normally on the bottom bar of the window (so I couldn't even pop up the play list).

Apple AppStore wanted to update Safari (to 9.1) so I did that, then cleared data/caches and tried starting Radiant Player again.  While it's changed from orange to blue, the pause/play button and playlist button are still missing in action.

**Comment by jlp78** [comment] 2016-03-24 21:53
![image](https://cloud.githubusercontent.com/assets/2334410/14032392/1d8317aa-f1d8-11e5-9528-368c422d3237.png)
NOTE: I didn't change anything that would have caused the colors to change.  After playing that song, it "played" (with no audio and at about 10 x normal speed) two more songs, then actually started playing the next one (of course, I can't see the playlist, so not entirely sure how many songs got skipped).

**Comment by jacobwgillespie** [comment] 2016-03-24 22:02
What does the Appearance settings tab look like?

<img width="397" alt="screenshot 2016-03-24 17 01 03" src="https://cloud.githubusercontent.com/assets/130874/14032622/1fb36ec6-f1e2-11e5-83c5-d5786c2fdfc5.png">

**Comment by jlp78** [comment] 2016-03-24 22:13
Maybe I did change something that caused the colors to change... my appearance tab says Style: Rdiant.  That probably covers the blue vs. orange, but the controls are still missing.  I just tried updating Adobe Flash to version 21a (the latest from adobe) and that didn't help, either.

**Comment by jlp78** [comment] 2016-03-24 22:16
Yep, changed style back to "Google" and the orange bar is back.  Funny that I don't remember changing that, but I must have flipped it while looking through the settings.  Sorry about the false alarm on that one.  Now I just need to get the playback controls and playlist popup back.

**Comment by jacobwgillespie** [comment] 2016-03-24 22:23
Can you post a screenshot of the window now (with the default style)?  I'm curious if anything else is off.

**Comment by jlp78** [comment] 2016-03-24 22:29
![image](https://cloud.githubusercontent.com/assets/2334410/14033105/3f47ece4-f1dd-11e5-8765-8d3c22903ebc.png)

FYI, I've also tried removing Library/Preferences/com.sajidanwar.Radiant-Player.plist, Library/Caches/com.sajidanwar.Radiant-Player, and Library/Application Support/Radiant Player, just to make sure I was starting with a clean slate.

Oddly enough, while I had to re-login with Google, Last.fm seemed to still retain it's state.  It must not be keeping its credentials in the normal location.

**Comment by jacobwgillespie** [comment] 2016-03-24 22:36
Yeah, it still looks broken in other ways too - can you try opening Google Play Music in Safari and see if you experience the same issue?  You might also try clearing your Safari cache.

**Comment by Macca-MK** [comment] 2016-03-25 14:31
Just checked on my home machine (running El Capitan) and have no problems at all - everything about the UI seems correct and Playback controls appear and work fine. 

Assuming a Yosemite issue then?

**Comment by paul-turner** [comment] 2016-03-25 17:25
Safari seems to be laying things out fine:
![screen shot 2016-03-25 at 1 23 22 pm](https://cloud.githubusercontent.com/assets/1944943/14049621/d4f0d616-f28c-11e5-89fd-5cbf4206421c.png)
Vs radiant player:
![screen shot 2016-03-25 at 1 23 32 pm](https://cloud.githubusercontent.com/assets/1944943/14049634/df14f5dc-f28c-11e5-8180-f8cac749563e.png)


Yosemite 10.10.5 here with Safari Version 9.0.3 (10601.4.4)

**Comment by jlp78** [comment] 2016-03-25 17:42
Yes, it looks good in Safari for me, too.  Yoseite 10.10.5 here, also.  Safari 9.1 (10601.5.17.4).

Radiant Player is still messed up.  RP version 1.7.3.

**Comment by chrismou** [comment] 2016-03-25 18:00
I did notice yesterday that our build target is OSX 10.8.  Could be that that's determining which version of Safari is uses to render, but I'm just speculating.  I'll have a dig around this weekend.

**Comment by jacobwgillespie** [comment] 2016-03-25 18:10
People who are experiencing a broken interface, can you download this custom build, then right-click on a blank part of the page, choose Inspect Element, then choose the Console tab and screenshot that?  Depending on the amount of items logged in the console, you may have to take multiple screenshots.  It's best if you do this after reloading the app (either just after starting it or with CMD-Shift-R).

[radiant-player-web-debug.zip](https://github.com/radiant-player/radiant-player-mac/files/189866/radiant-player-web-debug.zip)

Here's an example screenshot:

<img width="1449" alt="screenshot 2016-03-25 13 10 00" src="https://cloud.githubusercontent.com/assets/130874/14050575/ece3d572-f28a-11e5-90e9-ecc2276e7dfa.png">

**Comment by paul-turner** [comment] 2016-03-25 19:00
Here ya go:
<img width="1548" alt="screen shot 2016-03-25 at 2 59 32 pm" src="https://cloud.githubusercontent.com/assets/1944943/14051546/3f2a8e16-f29a-11e5-9713-194b2a37704f.png">

**Comment by jlp78** [comment] 2016-03-25 19:17
Here's mine:

![image](https://cloud.githubusercontent.com/assets/2334410/14051912/cd0e14f0-f28b-11e5-98d6-42a4dc8ace1c.png)
![image](https://cloud.githubusercontent.com/assets/2334410/14051927/e7050918-f28b-11e5-971c-90e674415e21.png)

**Comment by jacobwgillespie** [comment] 2016-03-25 20:51
Thanks for those - @jlp78, yours appears "normal" (same as mine), @paul-turner, yours has one interesting failure on the line here: https://github.com/radiant-player/radiant-player-mac/blob/cb308b9c43982cf23507cb7faa5246fdb243632a/radiant-player-mac/js/navigation.js#L70.  However as best as I can tell it's just failing because the navbar isn't there, which we already knew.

I don't think it's directly related, but I submitted PR #526 to clear out the console errors related to our code (Google's code emits a few of those errors too).  I don't think that'll change anything here though.

This does seem Yosemite-related though, so like @chrismou said we may want to look into what version of WebKit we're building against.

**Comment by jacobwgillespie** [comment] 2016-03-26 14:15
There's a new version 1.7.4 - I don't think it will fix this issue here, but it wouldn't hurt to update and let me know if anything changes.

**Comment by jlp78** [comment] 2016-03-27 03:03
1.7.4 does not fix the problem for me.

**Comment by BarakaAka1Only** [comment] 2016-03-28 22:04
Okay so with the debugging (I enabled dev tools in safari) with the stylesheet listenstyles.css for every ~flex:~ item it was getting ignored 
<img src="http://i.imgur.com/EmzFyRK.png" />
so i extracted that stylesheet and changed everything with adding -webkit to it from there i pasted in the changes and it worked everything is fixed that way with -webkit added not sure why it's getting ignored 

but for anyone that wants to try my edited version here is the link to it:

https://www.dropbox.com/s/upo0enyc4miu6ir/google-baraka.css?dl=0

**
(Not sure if you need to enable devtools in safari itself but i enabled it just-incase either way inspect element should be there)**

Apply enable devtools in safari (Preferences > Advanced> check off Show Develop menu) and then run Radiant-player right-click anywhere and inspect element.

In the Resources tab click on Stylesheets and the last item should be listenstyles.css

select all and replace with my modified css and you should see it fixed instantly, if you don't Radiant-player has to be loaded fully but it will work.

<img src="http://i.imgur.com/Ht4Iysu.png" />

**Comment by dstockto** [comment] 2016-03-28 22:40
The suggestion above that @BarakaAka1Only posted worked for me. Without it, all the listen now stations just had a background but nothing playable. I could hover over blank areas of the screen and get a couple of play buttons to show up on hover.

My screenshot before the fix above with 1.7.4:

![image](https://cloud.githubusercontent.com/assets/775393/14092404/cc89dd8c-f503-11e5-978f-ce569a7ec054.png)

**Comment by BarakaAka1Only** [comment] 2016-03-28 23:19
Great to hear that it worked for you @dstockto 

@ the devs i remade the css with only the areas where flex was added so it won't "overload" / interfere with styles, in short this is a flex only css sheet that adds -webkit rules to the selectors that it is needed only :) 

https://www.dropbox.com/s/n3pbl1r8dwurf2p/google-baraka-flexonly.css?dl=0

**Comment by jacobwgillespie** [comment] 2016-03-28 23:37
@BarakaAka1Only awesome, thanks for that debugging!  I've submitted PR #529 to resolve this issue and as soon as it's reviewed I'll push out a new version.

**Comment by BarakaAka1Only** [comment] 2016-03-28 23:39
Not a problem, i had to fix one z-index issue on the sidebar i updated my css and the link above sorry about that.

**Closed** 2016-03-29 17:13 UTC

**Comment by jacobwgillespie** [comment] 2016-03-29 17:15
Just merged the fix - it should go out as 1.7.5 in the next few minutes

**Comment by mjessome** [comment] 2016-03-29 18:24
Thanks for the quick fix!

**Comment by antwonw** [comment] 2016-03-29 18:56
Just updated in-app to 1.7.5. Has been fixed for me (on OS X 10.10.5).

**Comment by jlp78** [comment] 2016-03-29 18:59
Yep, 1.7.5 looks good!

**Comment by Macca-MK** [comment] 2016-04-06 10:13
Took so long getting round to checking this (been on hols) that we're now
on 1.8.2, and the problems have all been resolved.

Thanks everyone for your help!

On 29 March 2016 at 21:02, Baraka <notifications@github.com> wrote:

> :D No problem, glad i could help ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/radiant-player/radiant-player-mac/issues/523#issuecomment-203075404>
>



-- 
*Andrew McDermott*
andrewmcdermott.mk@gmail.com
