### ISSUE TITLE
AppleScript dictionary appears blank

### ISSUE THREAD

**Issue by TheRealGitCub** [radiant-player/radiant-player-mac#350] opened 2015-08-16 05:00 UTC
AppleScript definitions are included in `radiant-player-mac/radiant-player-mac/AppleScript/radiant-player-mac.sdef`, however the dictionary appears blank for me. I only see a message that says "Nothing to see here"

Running OS X 10.10.5  
Script editor 2.7  
AppleScript 2.4

**Comment by jacobwgillespie** [comment] 2015-12-04 19:09
I'm not super familiar with AppleScript - can you give some steps to reproduce?

**Comment by chrismou** [comment] 2015-12-04 20:30
Hey @TheRealGitCub - I'm not 100%, but could this be a similar issue as reported here: https://github.com/radiant-player/radiant-player-mac/issues/422 ?

If so, could you try against a build from the master branch and see if the issue is still there?  

I put up a recent build for a recent PR if you prefer, save you booting up Xcode: https://github.com/chrismou/radiant-player-mac/releases/download/v1.5.0-cyan/RadiantPlayer.app.zip

**Comment by jacobwgillespie** [comment] 2016-03-31 15:41
I'm closing this for now - feel free to post back if you're still experiencing issues.

**Closed by jacobwgillespie** 2016-03-31 15:41 UTC
Labels: can't reproduce
