### ISSUE TITLE
Broken Black theme

### ISSUE THREAD

**Issue by temnoregg** [radiant-player/radiant-player-mac#373] opened 2015-10-14 14:45 UTC
Song listing row background is white instead of dark

![White background](https://dl.dropboxusercontent.com/u/6562716/Screen%20Shot%202015-10-14%20at%2016.41.21.png)

**Comment by shawn-mitch** [comment] 2015-10-14 16:53
I've noticed this too

**Comment by shawn-mitch** [comment] 2015-10-14 17:24
I've fixed the CSS. Until I create a pull request and it gets merged, you'll have to manually change the CSS file. Replace /Applications/Radiant Player.app/Contents/Resources/css/spotify-black.css with the file located here: https://dl.dropboxusercontent.com/u/11595858/spotify-black.css

**Comment by JustinTBrown** [comment] 2015-10-14 18:40
This did the trick - Thank you @shawn-mitch.

**Comment by IanMcNelly** [comment] 2015-10-15 22:32
Confirmed, fix works @shawn-mitch

**Comment by PaulMcAdam** [comment] 2015-10-21 13:39
Thanks :+1:

**Comment by planetmadness** [comment] 2015-10-23 09:19
The fix should actually be:
.material .song-row .column-content {
    background-color: **rgba(18, 19, 20, 0.98);**
}
**not**
.material .song-row .column-content {
    background-color: #000;
}

This breaks the semi-transparent design of the queue. Also it is not even the right color.

**Comment by shawn-mitch** [comment] 2015-10-23 14:47
@planetmadness First off, good job on noticing that. This was only meant as a temporary fix. Change here was only meant to restore functionality of the black theme. Secondly, don't be a jerk. Your fix isn't correct either. It should be 

.material .song-row .column-content {
  background-color: transparent;
}

If you're going to be nit-picky about temporary fixes, you should at least check your own code first.

The updated code, since the pull request hasn't been merged, is here: https://dl.dropboxusercontent.com/u/11595858/spotify-black.css

**Comment by planetmadness** [comment] 2015-10-23 23:48
@shawn-mitch never meant it as a dick move. Just seemed wrong to replace it with an less obvious but still incorrect color.
Like you said, the pull request hasn't been merged, so this temporary fix is still needed. Meaning that there's no harm in improving it.

The code you just suggested results in no visual difference. It just makes it slightly easier to change the queue background if one ever desired to do so. Not a huge improvement, but an improvement nonetheless. And like I said, there's no harm in improving fixes if they're needed.

Besides, this was never about functionality. Only about a hideous looking queue.

**Comment by kbhomes** [comment] 2015-10-24 07:29
I'm closing this issue because I've merged #374. Thanks @shawn-mitch and @planetmadness.

**Closed by kbhomes** 2015-10-24 07:29 UTC
