### ISSUE TITLE
ummmmmm...this seems to need flash.....why?!?!?!?

### ISSUE THREAD

**Issue by rchrdnsh** [radiant-player/radiant-player-mac#568] opened 2016-07-12 19:42 UTC
please leave flash out of this app, which feels like a webview, not a native macOS app... :-/

**Comment by jacobwgillespie** [comment] 2016-07-12 20:20
Radiant is built on Safari webviews (built into OSX native apps), and Google has not built HTML5 support for Safari.  We're working on the next version of Radiant that uses embedded Chrome technologies that will allow for HTML5 support, but it's not ready yet (no estimates on completion yet as we all work on this in our free time, but I'm hoping to get it out soon).

tl;dr - Flash is necessary for now, but soon won't be.

**Comment by ccampbell** [comment] 2016-08-02 05:51
I think this is a duplicate of #335?

**Comment by jacobwgillespie** [comment] 2016-08-02 12:07
Yep, closing as duplicate

**Closed by jacobwgillespie** 2016-08-02 12:07 UTC
Labels: enhancement
