### ISSUE TITLE
Scrolling down to the bottom of the 'Shared with me'

### ISSUE THREAD

**Issue by florida** [radiant-player/radiant-player-mac#204] opened 2014-07-09 17:41 UTC
I can't really capture the bug really really well with my screen recorder, but basically when I scroll down the 'Shared with me' tab to the bottom and keep scrolling, the striped colours starts doing weird stuff.

**Comment by jacobwgillespie** [comment] 2015-12-19 17:33
I'm going to close this as I cannot reproduce anymore, though feel free to ping if you're still experiencing issues.

**Closed by jacobwgillespie** 2015-12-19 17:33 UTC
