### ISSUE TITLE
Not working with OS X Yosemite 10.10.5

### ISSUE THREAD

**Issue by mickeymoso** [radiant-player/radiant-player-mac#603] opened 2016-09-14 20:33 UTC
Not working with OS X Yosemite 10.10.5
EDIT: fixed with new update 1.10.3
Fixes #603

**Comment by tjanson** [comment] 2016-09-14 20:35
Please check whether this is a duplicate of #589 (you'll find some workarounds there too).

**Comment by Zhomart** [comment] 2016-09-14 21:42
I found fix on #600 commenting out 2 lines in file `/Applications/Radiant Player.app/Contents/Resources/js/navigation.js` comment out lines 70, 71.

**Comment by mmaybeno** [comment] 2016-09-14 22:10
This helped a similar issue I had on macOS version 10.11.6. Commenting 70, 71 out fixed it for now.

**Comment by tjanson** [comment] 2016-09-14 22:13
Please close this issue in favor of #589 unless there you’re sure this is a separate problem (and if so, please provide more detail). Splitting the discussion over several duplicates will makes it harder to find the solutions.

**Closed** 2016-09-15 00:33 UTC
