### ISSUE TITLE
Large album-art view causes ~100% cpu utilization

### ISSUE THREAD

**Issue by jscheel** [radiant-player/radiant-player-mac#471] opened 2015-12-28 20:15 UTC
Watch cpu usage spike when you click the album art at the lower left corner (to fill the screen with the album art). Running build from master.

**Comment by jacobwgillespie** [comment] 2015-12-29 05:22
How high are you seeing?  I'm able to reproduce in Radiant as CPU 22% "normal" then 99% when the album art is enabled.  However, I'm seeing similar numbers in Safari and Chrome actually went up to 140%.  Depending on what you're seeing, we may want to mark this as a Google issue and close.

**Comment by jscheel** [comment] 2015-12-29 15:08
Yeah, I'm betting it's a google issue. In chrome the playing equalizer gif runs the cpu up to 30-40% as well. Wonder if we can do some theme tweaks to get it to use gpu acceleration if possible.

**Comment by jacobwgillespie** [comment] 2015-12-31 19:02
I'm going to close this for now since we can reproduce in Chrome, but feel free to comment back if anything new comes up.

**Closed by jacobwgillespie** 2015-12-31 19:02 UTC
