### ISSUE TITLE
Freezing and Locking Up

### ISSUE THREAD

**Issue by jdcliff** [radiant-player/radiant-player-mac#489] opened 2016-01-25 20:00 UTC
Been trying to use Radiant for a few weeks now, and have run into this same problem over and over again. Everything works right up until I choose a playlist/album/song, then any mouse clicks after that either don't work at all or screen never loads correctly when trying to back out of a playlist. The music keeps on playing, but there is no functionality to change songs. 

CMD-Q kills is, and then I have to reload it to find a different album. 

Using 2013 Macbook Air.

**Comment by marcelocf** [comment] 2016-01-26 01:07
Same thing here.

**Comment by chrismou** [comment] 2016-01-26 13:35
@jdcliff @marcelocf When the app freezes, if you resize the window slightly does it become responsive again?

That's not a permanent fix obviously, just interested to know if this is the same issues as we've seen reported before, or something different.

**Comment by marcelocf** [comment] 2016-01-26 13:38
I will try next time it happens but I think I can't resize at all. Will
confirm here tomorrow (Japan time)

Marcelo C. Freitas

**Comment by jdcliff** [comment] 2016-01-26 20:46
Totally fixed the problem. Strange work-around, but resizing does the trick
right now.




On Tue, Jan 26, 2016 at 7:35 AM Chris Chrisostomou <notifications@github.com>
wrote:

> @jdcliff <https://github.com/jdcliff> @marcelocf
> <https://github.com/marcelocf> When the app freezes, if you resize the
> window slightly does it become responsive again?
>
> That's not a permanent fix obviously, just interested to know if this is
> the same issues as we've seen reported before, or something different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiant-player/radiant-player-mac/issues/489#issuecomment-175014543>
> .
>
-- 

*Jonathan Cliff*
*Grace Community Church* || Connection Pastor
|| +931.614.7790 || jcliff@graceclarksville.com
<jcliff@graceclarksville.com>

* <http://www.graceclarksville.com/>*

* <http://meetme.so/JonathanCliff>*

**Comment by chrismou** [comment] 2016-01-26 20:51
Strange eh? :-/

I've got a pull request in for a potential fix (#480) but I've noticed a few issues with it that need ironing out before I merge it in.  Hoping to land it in the next few days - I'll drop a message here when I do.

**Comment by marcelocf** [comment] 2016-01-27 05:09
I managed to reproduce this. A couple of more details on this issue:

* it seems to happen more often when using the default style. Since I
switched to black style it seems more responsive - might be just my
impression.
* I kept browsing my library the entire morning with no problem. It only
behaved badly after the computer went to sleep.
* the resize trick did solve the problem and I browsed the library just
fine after doing so.

I saw your pull request regarding the custom title bar. Do you have a build
for that so I can test it?


Marcelo C. Freitas

**Comment by chrismou** [comment] 2016-01-27 11:37
@marcelocf 

[radiant-player.zip](https://github.com/radiant-player/radiant-player-mac/files/106510/radiant-player.zip)

This is my local build in it's current state. Few more tweaks to make, but the proposed fix is there.  FYI, most people report the issue showing itself after minimizing the app for a while then bringing it back to focus, so I guess seeing it after the Mac wakes up from sleep is a similar scenario.

**Comment by oojacoboo** [comment] 2016-01-29 02:57
I've been having this same issue since I downloaded the app.  I found that clicking on the "X" for the app window and holding it down for a sec, then dragging off and releasing while not hovering over the "X", basically just not closing the app, causes the same effect as the resize window hack.

It does really suck you have to do this.

**Comment by S-Seahorse** [comment] 2016-01-29 08:01
A very odd plot twist, I've noticed that when it freezes like this, the player only refreshes while the mouse is being moved, it stops when the mouse stops.

**Comment by chrismou** [comment] 2016-01-29 15:06
@oojacoboo @S-Seahorse @marcelocf @jdcliff 

Pre release build is here: https://github.com/chrismou/radiant-player-mac/releases/tag/1.7.0-pre

Would appreciate having a quick test to see if it fixes the issue for you, if you get some time.  Will probably release this weekend, pending any major issues.

**Comment by oojacoboo** [comment] 2016-01-29 21:30
@chrismou better, but it's still not fixed.  It's fixed initially when you open it up.  However, it still has a tendency to go back to the frozen state after clicking through to something.

**Comment by chrismou** [comment] 2016-01-29 21:41
@oojacoboo Is that even with the custom title bar switched off?

**Comment by chrismou** [comment] 2016-01-29 21:46
And when you say "clicking through to something" can you describe exactly what you're doing? I've been seeing the freezes for a while, but it only ever happens for me whe I minimise the player then bring it back into focus

**Comment by oojacoboo** [comment] 2016-01-29 21:51
Sorry, didn’t know about the need to disable the custom title bar.  It does seem better with that disabled.  I’ll keep testing.  Thanks!

……………………………………………………………..

Jacob Thomason

Ackoo  •  ackoo.com

http://https//rentpost.com
Voice:  478.361.1263

Fax:  866.329.1596

On Fri, Jan 29, 2016 at 4:46 PM Chris Chrisostomou

<
mailto:Chris Chrisostomou <notifications@github.com>
> wrote:

And when you say "clicking through to something" can you describe exactly what you're doing? I've been seeing the freezes for a while, but it only ever happens for me whe I minimise the player then bring it back into focus

**Comment by chrismou** [comment] 2016-02-10 19:45
This should essentially be fixed in 1.7.  If you're still experiencing issues, feel free to open another ticket

**Closed by chrismou** 2016-02-10 19:45 UTC
