### ISSUE TITLE
Memory and CPU leak on Yosemite

### ISSUE THREAD

**Issue by plmcgrn** [radiant-player/radiant-player-mac#336] opened 2015-06-19 02:51 UTC
It seems that the most recent update that fixed the issue with Google Music's new design, introduces a nasty CPU and memory leak if you leave it open over time.

I noticed that memory will exceed 1GB in about 48 hours, and CPU will easily be consistently above 30%.  When left open long enough, it will overwhelm CPU and easily eat 2-4GB of memory.

![image](https://cloud.githubusercontent.com/assets/889547/8246410/1d694706-160c-11e5-8a8f-84a88cf7903f.png)

**Comment by wfortin** [comment] 2015-06-19 15:13
I am experiencing the same issue.

**Comment by doque** [comment] 2015-06-25 14:05
Same here:
![screen shot 2015-06-25 at 16 04 12](https://cloud.githubusercontent.com/assets/1480751/8356170/0a3f0e52-1b54-11e5-9c05-69b598bc8222.png)

**Comment by Tuinslak** [comment] 2015-06-26 16:23
![screen shot 2015-06-26 at 18 21 04](https://cloud.githubusercontent.com/assets/306680/8382082/5ff945a6-1c30-11e5-88eb-c3addf403c10.png)

Confirmed... :)

**Comment by morganhi** [comment] 2015-06-30 22:41
..yup :/

**Comment by dodgepong** [comment] 2015-07-01 15:49
Same issue here. Activity Monitor reported Radiant Player using over 13 GB of memory this morning after leaving it open for several days. Restarted it and it's back down to ~350 MB, but I expect it to go back up eventually.

**Comment by ArtRoman** [comment] 2015-07-06 17:51
OS X 10.9.5, RadiantPlayer consumes memory and CPU after number of uptime days. Old version without material Music was working fine. Spindump says about a lot of operations in JavaScriptCore. 
Music in Chrome works great even after some days of uptime without page reloading.

![2015-07-06_19 22 20](https://cloud.githubusercontent.com/assets/1625142/8527417/2c08a2b8-2415-11e5-8898-113207428129.png)

**Comment by chumbothewhale** [comment] 2015-07-09 02:28
Same here.

![screenshot 2015-07-08 19 25 33](https://cloud.githubusercontent.com/assets/7739108/8586743/4fd527fa-25a7-11e5-92ff-89d878583129.png)

**Comment by joeljfischer** [comment] 2015-07-14 14:49
Same as #328

**Comment by larouxn** [comment] 2015-08-05 18:15
Issue still persists today. OS X 10.10.4
CPU (I've seen as high as 77%):
<img width="565" alt="screen shot 2015-08-05 at 14 13 55" src="https://cloud.githubusercontent.com/assets/1557529/9093816/4460ca56-3b7c-11e5-930f-a93028750eaf.png">
Memory:
<img width="542" alt="screen shot 2015-08-05 at 14 09 28" src="https://cloud.githubusercontent.com/assets/1557529/9093821/4c2d0fe2-3b7c-11e5-972c-05bd4fa4e24b.png">

**Comment by jadengore** [comment] 2015-08-28 17:26
Radiant Player has always had pretty heavy memory usage, but it's becoming unbearable in 1.4.0. Plus with the rollback of @jacobwgillespie's fix, it seems that a lot of these issues might not be fixed for a while.

**Comment by dodgepong** [comment] 2015-08-28 17:30
Peronsally I had to switch back to just using a normal browser window + Key Socket Media Keys extension so I could use my keyboard media keys with it. Radiant Player is completely unusable for me on a system where system resources are at a premium.

Honestly I'm started to get tired of there being no good desktop player for Google Music, temping me to move to Spotify, which I'd rather not do.

**Comment by serginator** [comment] 2015-09-10 06:55
As @martinlauer stated in #328, if you disable the option `Show mini player in menu bar` improves a bit the situation, but there's still the memory leak

**Comment by krisdestruction** [comment] 2015-09-29 19:24
I think this issue is actually reported in #308

**Comment by jadengore** [comment] 2015-12-14 06:50
Hey everyone,

As part of our Radiant 2 Milestone (more here #409), we are working to improve the performance of Radiant Player. I have begun profiling the memory issue and will let you guys know if I am able to figure out what is causing it.

**Comment by krisdestruction** [comment] 2015-12-31 01:13
Should this be closed since it's a duplicate of both #308 and #328 ?

**Comment by jacobwgillespie** [comment] 2016-03-31 16:29
Yep, I'll close it as a duplicate of those two other issues.

**Closed by jacobwgillespie** 2016-03-31 16:29 UTC
Labels: performance
