### ISSUE TITLE
Song stopping early?

### ISSUE THREAD

**Issue by ckcollab** [radiant-player/radiant-player-mac#339] opened 2015-06-24 21:37 UTC
When listening to an instant mix the songs seem to be stopping at least ~10s early? Using 1.4.0 in Mac Mavericks

**Comment by ivancamilov** [comment] 2015-07-19 14:55
Same thing begun to happen to me a few days ago.

**Comment by kbhomes** [comment] 2015-07-27 17:43
Are these problems also existent in Safari?

**Comment by jacobwgillespie** [comment] 2015-11-24 05:42
I'm unable to reproduce, so closing for now - feel free to ping if you're still experiencing.

**Closed by jacobwgillespie** 2015-11-24 05:42 UTC

**Comment by ckcollab** [comment] 2015-11-24 06:09
Will do, thanks for the hard work!
