### ISSUE TITLE
App does not close/quit

### ISSUE THREAD

**Issue by mohnjatthews** [radiant-player/radiant-player-mac#410] opened 2015-11-12 10:45 UTC
Application does not close for some reason, I have to force quit the program every time to get it to stop. This happens regardless of whether or not I'm playing music.

Running Yosemite (10.10.5) on Mid 2010 iMac 27-inch. Radiant Player version 1.5.0

To recreate the issue:
   - Open Radiant Player
   - Right click on the icon in the dock
   - Go to Options and select Keep In Dock
   - In the app click on the close button at the top left (the app will minimise back into the dock)
   - Right click on the icon in the dock
   - Click Quit

It is at this point that I would expect the app to fully stop, but it doesn't. To then fully close the app you'll need to:
   - Click on the Apple icon in the top left of the screen
   - Click on Force Quit
   - Select Radiant Player
   - Click on Force Quit

Anyone else having this issue?

UPDATE: It looks like the app closes fine if you go to the options menu at the top and use Quit Radiant Player in there.
   - Open Radiant Player
   - Click on Radiant Player in the taskbar at the top left
   - Click Quit Radiant Player
OR
   - Press CMD + Q when Radiant Player is open

**Comment by Squintz82** [comment] 2015-11-12 16:35
I have a similar issue where I can't shut down with RP open. I have to manually close RP first.

**Comment by chrismou** [comment] 2015-11-12 16:40
For reference, this is (sort of) the same as #405.  Same issue, different scenario

**Comment by rwoodpecker** [comment] 2015-11-13 02:40
Same issue with me. Have to force quit it. Running latest El Capitan.

**Comment by crankeye** [comment] 2015-11-14 04:39
Also getting this issue after upgrading to El Capitan. I noticed if you close after immediately starting the app before it's fully loaded it will quit fine. However once the application has loaded I am unable to close it by right clicking and going to "close". Although I am still able to close it by pressing CMD + Q.

**Comment by can3p** [comment] 2015-12-01 10:31
I also have problem with closing the app via dock menu, Mac OS X 10.10.5

Steps to reproduce:
- Open context menu
- Click on quit menu item

In my case nothing happens with the player, playback doesn't stop, application doesn't halt.

If I open player window and press cmd-q, app quits in a usual way

**Comment by grimtastic** [comment] 2015-12-04 04:49
Same here. On OSX 10.11.1 and Radiant Player 1.5.0. Only happened since updating this latest version of RP. It's annoying because I will try to shut down my computer and it won't do anything until I force quit RP.

**Comment by jacobwgillespie** [comment] 2015-12-04 17:46
Looking into this now...

**Comment by jacobwgillespie** [comment] 2015-12-04 17:51
This is the change that broke this: https://github.com/radiant-player/radiant-player-mac/compare/59a66296d07292d5cb33ef6c40fd8b0d623d6249...59461481588691300ddf8132495bff712b802367

Now just gotta figure out what that's affecting...

**Comment by jacobwgillespie** [comment] 2015-12-04 20:10
There's a fix in #432 - should be merged soon.

**Closed** 2015-12-04 21:07 UTC
