### ISSUE TITLE
Won't finish loading library on Yosemite 10.10.5

### ISSUE THREAD

**Issue by connercowling** [radiant-player/radiant-player-mac#601] opened 2016-09-14 16:41 UTC
Library will not finish loading.  Gets stuck here:

<img width="952" alt="screenshot 2016-09-14 11 40 42" src="https://cloud.githubusercontent.com/assets/3486466/18521044/21cdc488-7a70-11e6-91e9-8709ac734b0b.png">

**Comment by TheCleric** [comment] 2016-09-14 16:48
Having the same issue on El Capitan (10.11.6)

**Comment by TheCleric** [comment] 2016-09-14 16:53
Looks like this is the same as issue #598

**Comment by tjanson** [comment] 2016-09-14 18:33
Please check whether this is a duplicate of #589 (you'll find some workarounds there too).

**Comment by connercowling** [comment] 2016-09-14 20:02
After taking a look at #589 and #600 I decided to try the 003 build from #589 and everything appears to be working fine. Thanks.

**Comment by tjanson** [comment] 2016-09-14 22:13
Cool :). Please close this issue in favor of #589.

**Closed** 2016-09-15 00:44 UTC
