### ISSUE TITLE
Nothing shows on the interface

### ISSUE THREAD

**Issue by rickette** [radiant-player/radiant-player-mac#575] opened 2016-07-28 07:44 UTC
Hi,

since last update (1.8.5) when i launch the programe nothing shows on the interface.
I can access my account, i can show the menu on the left but nothing appears in the center area.

I can still listen to playlist but when i click on an album or an artist, the the music stops, the interface reloads and nothing shows up on the screen.

I tried reinstalling the app but it didn't helped.

Anyone having the same issue ?
![capture d ecran 2016-07-28 a 09 44 34](https://cloud.githubusercontent.com/assets/11071486/17204824/ed5a7180-54a7-11e6-86b7-2e4ec86443f7.png)

**Comment by gnain** [comment] 2016-07-28 13:13
I've the same issue, and cannot even listen to playlists. Nothing loads or happens since the update this morning.

**Comment by chrismou** [comment] 2016-07-28 13:16
Hey guys

Could you right click somewhere in the window, and select "Inspect Element" in the context menu that pops up.  This should open the dev tools window - on the right, you'll see a Console tab.  Click that, then paste everything in that window into this issue  (or make it full screen and screenshot the output, if that's simpler).

**Comment by gnain** [comment] 2016-07-28 13:26
Here is my log from a fresh start of the App.
I just figured out (while inspecting) that a refresh (cmd+R on MAC) actually fills the page, and restores all functionalities back.
I can listen, see the illustrations and navigate.
````
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js, line 11)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] CustomError: Error in protected function: InvalidCharacterError: DOM Exception 5
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__fr.js, line 924)
```

**Comment by rickette** [comment] 2016-07-28 13:27
Here is mine : 

[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Warning] Unexpected CSS token: : (listen, line 426)
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js:11:21403)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:113)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:259)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:406)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 22886)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 22887)
[Error] CustomError: Error in protected function: InvalidCharacterError: DOM Exception 5
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__fr.js:924:359)
> Selected Element
< <div id="mainContainer" class="flex style-scope paper-header-panel">
<div id="music-content" class="material" role="main">…</div>
<sj-mini-queue id="queue-overlay" no-cancel-on-outside-click="true" role="dialog" tabindex="-1" aria-hidden="true" aria-modal="false" class="x-scope sj-mini-queue-0" style="outline: none; display: none;">…</sj-mini-queue>
<div class="dragging-target-line" style="display: none;"></div>
</div> = $1
[Error] CustomError: Error in protected function: InvalidCharacterError: DOM Exception 5
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__fr.js:924:359)
[Error] CustomError: Error in protected function: InvalidCharacterError: DOM Exception 5
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__fr.js:924:359)
	eAa (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__fr.js:915:83)
	(anonymous function)

**Comment by chrismou** [comment] 2016-07-28 13:31
I suspect `[Error] CustomError: Error in protected function: InvalidCharacterError: DOM Exception 5
    (anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__fr.js, line 924)` is the key here.  I wonder if it's related to the same thing that caused #572

Unless @jacobwgillespie has any thoughts, I'll have a look at this tonight and see if I can see what's changed

**Comment by gnain** [comment] 2016-07-28 13:39
@ rickette you have to have the inspector opened for cmd+R to refresh, otherwise, yes, it changes the repeat mode

**Comment by semka** [comment] 2016-07-28 17:47
Exactly the same here.

**Comment by smaspe** [comment] 2016-07-28 18:05
+1

**Comment by gl3b4ik** [comment] 2016-07-28 18:17
+1

**Comment by jacobwgillespie** [comment] 2016-07-28 18:31
You might try opening the web inspector (right click then pick Inspect Element), then `CMD-Shift-R` to force reload.

@chrismou it likely isn't the same thing as we're no longer overriding the global namespace on that JS.  I'm wondering if it has to do with the international versions of GPM...

**Comment by chrismou** [comment] 2016-07-28 18:40
@jacobwgillespie I've still not managed to recreate it, everything seems to be working fine at my end. I wondered if it might be an staggered GPM update rolling out, but if it is it hasn't reached me yet :-/

**Comment by graf** [comment] 2016-07-29 06:51
Here what i have

`
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js:11:21403)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:113)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:259)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:406)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] CustomError: Error in protected function: SyntaxError: DOM Exception 12
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__ru.js:947:359)
[Error] CustomError: Error in protected function: SyntaxError: DOM Exception 12
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__ru.js:947:359)
	fAa (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__ru.js:938:83)
	(anonymous function)
`

**Comment by chucheloff** [comment] 2016-07-29 12:07
same for me, worked on el capitan even without "use safari cookies" check, now nothing helps to play anything

**Comment by cytomich** [comment] 2016-07-29 12:17
I have the same issue.

**Comment by smaspe** [comment] 2016-07-29 15:06
It magically started working again after I opened the inspector and cmd+shift+r to reload. It reloaded fine and works. If I quit, I have to redo that procedure to make it work again.

**Comment by cytomich** [comment] 2016-07-29 15:17
@smaspe I'm also found this magic

But in my case, it not helps - half of the interface does not work, and I can't listen to music

**Comment by chucheloff** [comment] 2016-07-29 16:05
@smaspe this shift-reload only forces the home page to load, but still, nothing works and the whole thing reloads after each attempt to click something

**Comment by jacobwgillespie** [comment] 2016-07-29 16:15
For those experiencing the issue, can you let me know what country / locale you are using?  It seems that may be related.

**Comment by cytomich** [comment] 2016-07-29 16:22
@jacobwgillespie Russia / ru-RU

**Comment by cytomich** [comment] 2016-07-29 16:24
@jacobwgillespie 
errors from console

```
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js:11:21403)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:113)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:259)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:406)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] CustomError: Error in protected function: SyntaxError: DOM Exception 12
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__ru.js:947:359)
[Error] TypeError: undefined is not a constructor (evaluating 'new window.GMusic(window)')
	global code (main.js:12)
[Error] CustomError: Error in protected function: SyntaxError: DOM Exception 12
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__ru.js:947:359)
```

**Comment by semka** [comment] 2016-07-30 09:15
```
$ locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```

**Comment by rickette** [comment] 2016-08-01 08:48
I'm from France

**Comment by afunix** [comment] 2016-08-01 11:43
The same here in Russia.
Without Inspector only header is loaded, not page contents.
With Inspector the Home page is loaded, but upon play attempt I get page reload.

[Error] CustomError: Error in protected function: SyntaxError: DOM Exception 12
	c (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10__ru.js:947:359)

**Comment by ccampbell** [comment] 2016-08-02 05:55
I'm having the same issue, but for me the entire window is blank. I don't even have the top bar from the original screenshot:

![screenshot 2016-08-02 01 52 44](https://cloud.githubusercontent.com/assets/259316/17318383/eb79da04-5853-11e6-9f3b-65d074c852ef.png)

I'm in the US running OS X 10.9.5 (is Mavericks still supported?)

My console has:

```
[Error] Refused to get unsafe header "Location"
	getResponseHeader ([native code], line 0)
	(anonymous function) (webcomponents-lite.min.js, line 11)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	R (conversion.js, line 5)
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	R (conversion.js, line 5)
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	R (conversion.js, line 5)
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23287)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23288)
[Error] TypeError: 'undefined' is not a function (evaluating 'window.performance.getEntriesByType("resource")')
	nbb (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4778)
	C$ (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4778)
	init (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4890)
	init (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4905)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4905)
	(anonymous function) (listen, line 433)
	dispatchEvent
	(anonymous function) (webcomponents-lite.min.js, line 12)
```

**Comment by jacobwgillespie** [comment] 2016-08-02 17:02
> running OS X 10.9.5 (is Mavericks still supported?)

I'm not sure - it's more or less on Google's end how well they support older Safari runtimes from older OSX versions (which is what Radiant currently uses under the hood).  You are the first report (IIRC) if it breaking though.

**Comment by michaelsammler** [comment] 2016-08-02 20:39
I am in Japan with an american account and no VPN. Worked fine yesterday and this morning getting the white screen. Inspect Elements and CMD+SHIFT+R reloaded with an empty black screen. If anything from this is helpful let me know what to copy and paste. 
Love the program, I wish google would give you a heads up before making changes.
Michael
![screenshot 2016-08-03 05 36 16](https://cloud.githubusercontent.com/assets/10263082/17344323/a27e38f6-593c-11e6-98d4-9b06483f16c4.png)

**Comment by mattrobenolt** [comment] 2016-08-02 20:54
```
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Warning] Unexpected CSS token: : (listen, line 430)
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js:11:21403)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:113)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:259)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js:20:406)
	(anonymous function) (conversion.js:28:689)
	(anonymous function) (conversion.js:28:790)
	global code (conversion.js:29)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23287)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23288)
[Error] TypeError: window.performance.getEntriesByType is not a function. (In 'window.performance.getEntriesByType("resource")', 'window.performance.getEntriesByType' is undefined)
	nbb (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js:4778:135)
	C$ (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js:4778)
	init (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js:4890:469)
	init (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js:4905)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js:4905:136)
	(anonymous function) (listen:433:1610)
	dispatchEvent
	(anonymous function) (webcomponents-lite.min.js:12:6719)
```

Here, on 1.8.5 with 10.11.6.

**Comment by mordocai** [comment] 2016-08-02 21:22
I have the exact same log as @mattrobenolt and @ccampbell. American locale, and it just stopped working a few minutes ago for me.

**Comment by jrichocean** [comment] 2016-08-02 21:25
Same here, American locale

**Comment by mjelks** [comment] 2016-08-02 21:33
![screen shot 2016-08-02 at 2 31 42 pm](https://cloud.githubusercontent.com/assets/957738/17346084/f6ca6698-58bd-11e6-8da8-7cfb9295ca8f.png)

'Refused to get unsafe header "Location"' doesn't look good.

**Comment by puretekniq** [comment] 2016-08-02 21:54
Blank window in the USA. Also regular play music website not working for me in Safari.

**Comment by puretekniq** [comment] 2016-08-02 21:55
I'll donate $5 if this can get fixed.

**Comment by michaelsammler** [comment] 2016-08-02 22:14
Hopefully Jacob will probably comment on this, but I THINK this is just something that is going to happen every once in awhile cause google changes something that breaks 3rd party apps without giving any heads up, and Radiant player scrambles to figure out what is changed and gets things working again. 
Love Radiant Player and patiently waiting for it to get sorted.

**Comment by puretekniq** [comment] 2016-08-02 22:30
I just updated to latest OSX and it's still not working in Radiant player or Safari browser. I'm pretty sure Google broke it, but can it be fixed via Radiant player?? I hope so! I'm already super sad without my music.

**Comment by denangeles** [comment] 2016-08-02 23:41
Experiencing the same issues as ccampbell, Australian Locale.

Here is my console log:

> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Warning] Unexpected CSS token: : (listen, line 420)
> [Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
> 	Ea (conversion.js:20:113)
> 	(anonymous function) (conversion.js:28:689)
> 	(anonymous function) (conversion.js:28:790)
> 	global code (conversion.js:29)
> [Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
> 	Ea (conversion.js:20:259)
> 	(anonymous function) (conversion.js:28:689)
> 	(anonymous function) (conversion.js:28:790)
> 	global code (conversion.js:29)
> [Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
> 	Ea (conversion.js:20:406)
> 	(anonymous function) (conversion.js:28:689)
> 	(anonymous function) (conversion.js:28:790)
> 	global code (conversion.js:29)
> [Error] Refused to get unsafe header "Location"
> 	(anonymous function) (webcomponents-lite.min.js:11:21403)

**Comment by dstockto** [comment] 2016-08-03 00:34
17:43 $ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=

The console is this:

`[Warning] Unexpected CSS token: : (listen, line 420, x8)
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js, line 11)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23287)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23288)
[Error] TypeError: undefined is not a function (evaluating '[Warning] Unexpected CSS token: : (listen, line 420, x8)
[Error] Refused to get unsafe header "Location"
	(anonymous function) (webcomponents-lite.min.js, line 11)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Error] Blocked a frame with origin "https://2542116.fls.doubleclick.net" from accessing a frame with origin "https://play.google.com". Protocols, domains, and ports must match.
	Ea (conversion.js, line 20)
	(anonymous function) (conversion.js, line 28)
	(anonymous function) (conversion.js, line 28)
	global code (conversion.js, line 29)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23287)
[Warning] This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead (sj_srcs.js, line 23288)
[Error] TypeError: undefined is not a function (evaluating 'window.performance.getEntriesByType("resource")')
	nbb (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4778)
	C$ (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4778)
	init (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4890)
	init (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4905)
	(anonymous function) (listen_extended_80d882f312bf67807b5b6042e9718ae316b77d10.js, line 4905)
	(anonymous function) (listen, line 423)
	dispatchEvent ([native code], line 0)
	(anonymous function) (webcomponents-lite.min.js, line 12)
[Error] ReferenceError: Can't find variable: gmusic
	global code (listen, line 1)`

I have a completely blank window, not even the Radiant Player title shows like the screen above.

**Comment by davepagurek** [comment] 2016-08-03 00:35
So for me it seemed the issue was <a href="https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType">window.performance.getValueByType</a> not being defined in Safari, so I replace it with a function returning an empty array before other js is run and it fixes it for me. Can you check if this works for you too? https://github.com/radiant-player/radiant-player-mac/pull/578

**Comment by ccampbell** [comment] 2016-08-03 01:07
@davepagurek I can confirm that fixes it for me too. So this actually seems like a bug on Google's end. They shouldn't be using `window.performance` if it is not supported by the browser! 

I would be shocked if they weren't already aware of the issue and working on a fix.

**Comment by davepagurek** [comment] 2016-08-03 01:10
Yeah, I can understand them not bothering to get html5 audio working on Safari, but this completely breaks the app just for metrics tracking. I bet they'll fix it soon.

**Closed** 2016-08-03 02:38 UTC

**Comment by jacobwgillespie** [comment] 2016-08-03 03:04
Props to @davepagurek for the fix - it has been released as 1.9.0.

Sorry to all the international users, it appears you guys get your Google updates before we do in the US.

> this is just something that is going to happen every once in awhile

I've been working on Radiant 2.0 that uses Chromium under the hood (Electron) which should give better compatibility with Google.  Not ready yet but soon.

> I'll donate $5 if this can get fixed.

Donations are appreciated - once we get Radiant 2 ready I want to purchase an Apple signing certificate for security / distribution, which cost money.

**Comment by ccampbell** [comment] 2016-08-03 03:26
I'm not sure that that fix will work for the people who are getting `[Error] CustomError: Error in protected function: InvalidCharacterError: DOM Exception 5`, but it is working again for me! Thank you

**Comment by jacobwgillespie** [comment] 2016-08-03 03:30
True - please report back if 1.9 does not fix.

**Comment by puretekniq** [comment] 2016-08-03 04:01
A couple of notes:

1) 1.8.5 suddenly started working again for me as did Google play music in Safari. Perhaps they fixed it right at the same time?
2) I'm a little scared of Chromium. I used to use Chrome with GPM but it has bad issues with Bluetooth for me where it constantly disconnects, chops, etc. Safari has no such issues. I fear the switch to Chromium will make me stop using this, so I'd be happy to see an old safari-based build stay available for people like me. I'd be happy to do an early test to see if the compatibility issues carry over from Chrome if you're curious. Just let me know.
3) I'll totally donate. More than $5. Thanks for everything!

**Comment by jacobwgillespie** [comment] 2016-08-03 04:13
Sweet - I hesitate to draw attention to this link since it is so early, though it's public and been posted in the main repo before, but here's a test download of the new electron version: https://github.com/radiant-player/radiant-player-electron/releases/tag/v2.0.0-alpha-2.  Most things aren't working yet (see the notes [here](https://github.com/radiant-player/radiant-player-electron/releases/tag/v2.0.0-alpha) for some more detail).  But there's a chance it loads and a chance it runs faster than the current version.  It certainly does for me, because no Flash and GPM is optimized for Chrome.

If it doesn't work well for whatever reason, open an issue on the electron repository.  Electron (so Chromium-like) should be an improvement since that's the browser Google's targeting, but do let me know in an issue if you encounter any hiccups.

**Comment by rickette** [comment] 2016-08-03 07:37
Hi,

Just downloaded the 1.9.0 and apparently this doesn't solve the issue.
I tried rebooting and relaunching the app several times but this doesn't seem to fix it either.
