### ISSUE TITLE
stuck while loading 'My Library'

### ISSUE THREAD

**Issue by JuHwon** [radiant-player/radiant-player-mac#593] opened 2016-08-22 12:03 UTC
My Radiant Player always hangs when it is finished with loading my library (at least the loading bar is close to 100%).

![image](https://cloud.githubusercontent.com/assets/9406772/17854186/1eac0df2-6871-11e6-850d-1bb226704e8b.png)

**Comment by jacobwgillespie** [comment] 2016-08-22 13:08
Duplicate of #589 - we're looking into it.

**Closed by jacobwgillespie** 2016-08-22 13:08 UTC
