### ISSUE TITLE
Ability to change audio output target (e.g. usb connected speakers, etc)

### ISSUE THREAD

**Issue by megalithic** [radiant-player/radiant-player-mac#239] opened 2014-10-09 14:34 UTC
G-EAR has the ability to choose the audio output device (aside from the system-selected device), I'm not even asking for Airplay support which I've seen in previous logged issues that this is likely not to happen. Any chance of adding hardware connected output options? I use a USB DAC to my maudio av40's and would love to just output straight to them from Radiant. Thanks!

**Comment by fousheezy** [comment] 2015-11-18 15:47
+1

**Comment by jacobwgillespie** [comment] 2015-11-24 05:21
Duplicate of #228 - closing

**Closed by jacobwgillespie** 2015-11-24 05:21 UTC
