### ISSUE TITLE
"Couldn't fetch recommendations" error

### ISSUE THREAD

**Issue by stunnerstorm** [radiant-player/radiant-player-mac#621] opened 2016-11-15 15:52 UTC
Since yesterday, I've been getting this error on opening Radiant. I tried restarting the program and also reinstalling the program but I'm still getting it. I did recently upgrade to Sierra, so it might be a problem with that? I'm still able to access the other screens (top charts / new releases / music library / etc.) Only the "Home" screen is giving me this error. 

![screen shot 2016-11-15 at 10 45 47 am](https://cloud.githubusercontent.com/assets/23480925/20312440/80d25fa2-ab21-11e6-954f-a418507eae89.png)

**Comment by benmeroff** [comment] 2016-11-15 18:03
I was using Radiant Player with Sierra for weeks without issue until today, it seems a Google Play Music update may be the probable culprit...

**Comment by benmeroff** [comment] 2016-11-15 18:09
Yeah now that I looked at Google Play Music online, it looks like they just updated their "launch page" look where they show recently played and recommendations.

![screen shot 2016-11-15 at 12 06 15 pm](https://cloud.githubusercontent.com/assets/13946393/20317580/41aee812-ab2c-11e6-99b6-1fcb94f1f57f.png)

**Comment by shawn-mitch** [comment] 2016-11-16 20:36
I'm also seeing this issue. After a quick debug, it looks like the app is getting a 401 when trying to load the homepage. I haven't done any more research than that, but it's a start.

**Comment by afunix** [comment] 2016-11-17 15:35
+1

**Comment by jcooley8** [comment] 2016-11-17 22:02
+1

**Comment by tjanson** [comment] 2016-11-17 22:04
Guys, please, do not spam "+1", here or elsewhere. Nothing good comes of
it, but it sure is annoying. GitHub introduced reaction emotes precisely
for this reason.

**Comment by shawn-mitch** [comment] 2016-11-26 06:14
I figured it out! You just need to log out and log in again to get the new homepage to work in Radiant. The visuals need tweaking (especially if you're using one of the dark themes) but it works!
![screen shot 2016-11-26 at 12 13 25 am](https://cloud.githubusercontent.com/assets/5890308/20638426/49831dee-b36d-11e6-89a8-18d997caccb0.png)

**Comment by benmeroff** [comment] 2016-11-26 06:58
Can't try logging out and back in at the moment, but I'm glad you found a way to regain full functionality!

**Comment by robdoesstuff** [comment] 2016-11-29 21:50
Confirmed, logging out and logging back in worked.

**Comment by jacobwgillespie** [comment] 2016-12-13 17:03
I'm going to close this with the provided solution above of logging out and logging back in.

Feel free to post back if you're still experiencing issues.

**Closed by jacobwgillespie** 2016-12-13 17:03 UTC

**Comment by agarzola** [comment] 2017-03-21 12:45
This issue just popped up for me. Logging out and back in does fix the issue, but I wanted to note that I was still able to navigate to other sections of the app, like my library, playlists, new releases, etc. Only the Home section continually gave this error. I hope that’s helpful.
