### ISSUE TITLE
Mini player (with full cover) is updated only when main window is active

### ISSUE THREAD

**Issue by nashbridges** [radiant-player/radiant-player-mac#331] opened 2015-06-04 06:21 UTC
1.3.3.2-beta, 10.9.5

**Comment by kbhomes** [comment] 2015-06-05 03:16
Is it possible to capture a video of this scenario? Or more explicit steps to reproduce? I'm unable to reproduce this right now. :confused:

**Comment by nashbridges** [comment] 2015-06-05 06:20
Sorry, my bad.
When you open up mini player, the slider and seconds counter are frozen on a song current position. The artwork though is changed when the song is ended.
However, when you open up main window, then the slider begins to move forward synchronously.

**Comment by Justonian** [comment] 2015-06-11 23:35
I'm encountering the same behavior regarding the slider and progress bar being paused. With the main window open, it proceeds as expected.

**Comment by chrismou** [comment] 2015-12-13 02:37
Hey @nashbridges & @justonian  - I know this is a really old issue, but there's been a ton of fixes/improvements since it was logged.

If possible, could you check latest code and see if you're still seeing the issues you're reporting here? You can either build from master, or for convenience I've tagged a release on my fork of everything up to today: https://github.com/chrismou/radiant-player-mac/releases/tag/v1.5.0-20151213

Thanks!

**Comment by nashbridges** [comment] 2015-12-13 14:41
@chrismou I've tested your fork and the reported bug is fixed there. However, album art is not loaded neither in mini player, nor in dock (which obviously is an unrelated issue, but I've stopped using radiant player long time ago, therefore didn't send a report)

![image](https://cloud.githubusercontent.com/assets/380913/11767489/efcdfdcc-a1b7-11e5-8173-1121ab5b92bb.png)

**Comment by chrismou** [comment] 2015-12-13 17:11
Huh. That's interesting. I can't make my mini player look like that at all. I can't even get it to show the "playing" image in the status bar icon.

Thanks for getting back to me though. I'll look into the album art issue.

**Comment by chrismou** [comment] 2015-12-14 20:55
Hey @nashbridges - thanks for the heads up about the song art. Turns out Google made another change and it broke it. Now fixed - should be included in the new release

Cheers! :+1:

**Closed by chrismou** 2015-12-14 20:55 UTC
